version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: ecommerce-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=M12*117Go
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   
      - "15672:15672" 
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    ports:
    - "6379:6379"
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ecommerce-redisinsight
    ports:
      - "8001:5540" 
    restart: unless-stopped